### ISSUE TITLE
New release required for Hangar hotfix?

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [allista/AT_Utils#1]
With the Hangar 3.2.1.2 hotfix, the DLL loading chokes when it gets to Hangar.dll:

```
ADDON BINDER: Ingoring binding redirect due to incompatible versions: 002_MultiAnimators, Version=1.1.6213.41683, Culture=neutral, PublicKeyToken=null => 002_MultiAnimators, Version=1.1.6213.35278, Culture=neutral, PublicKeyToken=null
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

ADDON BINDER: Ingoring binding redirect due to incompatible versions: 001_AnisotropicPartResizer, Version=1.2.6213.41683, Culture=neutral, PublicKeyToken=null => 001_AnisotropicPartResizer, Version=1.2.6213.35278, Culture=neutral, PublicKeyToken=null
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

AssemblyLoader: Exception loading 'Hangar': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 
```
The loader then chokes on all of Hangar's classes and such.  The DLLs shipped with AT_Utils 1.3.1.1 are build 35278, but it looks like Hangar wants build 41683 (though I've never seen any other KSP mod so insistent about its dependencies' versions).

**Comment by allista** [comment]
Oh, heck! Thanks for the report. I'll change the versioning scheme of the child dlls to manual to prevent such accidents in the future. And reupload the archive for this release of AT_Utils.

Meanwhile you can just **use the release of the Hangar from SpaceDock**, which contains the dll with the right build number. I honestly don't know why it was changed (automatically), because the code was not, so aside from that number dlls should be identical.

**Comment by allista** [comment]
I've updated the archive. Installation from CKAN should not cause problems anymore, but AT_Utils need to be reinstalled to get dlls with correct version numbers.
