### ISSUE TITLE
Status of this compared to KSP 1.5?

### ISSUE THREAD

**Issue by AmberCronin** [allista/AT_Utils#9]
Just wondering when this is going to be updated. No rush, just would like to know if/when I should start building for 1.5 as my mod requires this as a dependency. Thanks!

**Comment by allista** [comment]
And when, pray tell, have the 1.5 been released? :)
I, personally, became aware of it from your issue just now >_<

Anyways, it depends on the things that have been changed. If it's a matter of recompilation, it's this weekend; otherwise, honestly, no idea. I don't have much time to spare between the job, the wife and the child (and the dog, and two cats, oh boy!) =^_^=

Tell you what: your dependence on AT_Utils makes you an interested party =] So maybe you could help. There's now [The Master of Them All](https://github.com/allista/AT_KSP_Plugins) repo for my plugins that makes it much easier to build from scratch. You just need to clone it with submodules (the README lists the command), an you'll have all the interdependencies in place. Will only have to place the `KSP_Data` directory where `.csproj` files expect it to be (relative to the whole thing). _There's even a handy script to change all the references at once, but it requires python and my [PyKSPutils](https://github.com/allista/PyKSPutils) library installed; and a Unix system for that matter..._

So, you can try to recompile the whole solution against the new KSP dlls and tell me what happens? :)

**Comment by AmberCronin** [comment]
Alright, I managed to download this and it's submodules... :p (ssh keys are a hell of a drug)  
AT_Utils compiles fine with 1.5 .dlls, only two warnings on depreciated functions (Part.RequestResource). 
 
On the topic of everything else...  
I have no idea how to do it :p. All these submodules and sub-sub-modules and everything have confused me to no end...  
I hope this helps at least a little bit. My guess is that not much else changed, and that a lot of the submodules that you have will just require a re-compile without any changes.

**Comment by allista** [comment]
That's good to hear! The I'll make the release on Sunday or Monday.
Thanks!

**Comment by allista** [comment]
Sorry, but my job messed all the plans again. Don't actually know when I'll have time for KSP again. So it's good thing you've managed to setup the workspace. On the other hand, deprecation warnings don't hurt, so it should be safe to use current dlls as is.

**Comment by AmberCronin** [comment]
I can send you the .dll for AT_Utils compiled against 1.5.x, if you¡d like to release that…

**Comment by allista** [comment]
Nah, don't have time for that. It'll require to rerelease all the dependants.
